variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  PROJECT_DIR: "/home/ubuntu/my-app"
  SERVICE_NAME: "app"

stages:
- build
- deploy

build:
  stage: build
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  - docker build -t $IMAGE_NAME:$IMAGE_TAG .
  - docker push $IMAGE_NAME:$IMAGE_TAG
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  needs: [ "build" ]
  before_script:
  - chmod 400 "$SSH_PRIVATE_KEY"
  script:
  - |
    scp -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" \
      docker-compose.yml \
      deploy.sh \
      ubuntu@54.179.124.196:"$PROJECT_DIR/"

    ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" ubuntu@54.179.124.196 "
      cd $PROJECT_DIR &&
      echo \"$CI_REGISTRY_PASSWORD\" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY &&
      docker pull $IMAGE_NAME:$IMAGE_TAG &&
      chmod +x deploy.sh &&
      IMAGE_NAME=$IMAGE_NAME IMAGE_TAG=$IMAGE_TAG SERVICE_NAME=$SERVICE_NAME ./deploy.sh
    "
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
